import { Map } from "./core/map";
import { BasePage } from "./pages/BasePage";
import { Objects } from "./core/Objects";
import { NavController } from "./core/NavController";
import { ConfirmButtons, Alert } from "./core/simple_confirm";
import { Dialog, DialogPage } from "./pages/DialogPage/DialogPage";
import { Translate, ReplaceValues } from "./core/Translate";
import { Injector } from "./core/Injector";
import { SimpleTabs } from "./components/SimpleTabs/SimpleTabs";
import { MenuPage } from "./pages/MenuPage/MenuPage";
import { ActionSheetPage } from "./pages/ActionSheetPage/ActionSheetPage";
import { DeBouncer } from "./core/DeBouncer"; 
import { DateTime } from "./core/DateTime";
import { DataShape } from "./core/DataShape";
import { CallbackQueue } from "./core/CallbackQueue";
import { Analytics } from "./core/analytics_matomo";
import { OptionsDialogPage } from "./pages/OptionsDialogPage/OptionsDialogPage";
import { Extend, GUID, Override, tryCall } from "./core/helpers";

import { Toast, ToastPage } from "./pages/Toast/Toast"; 
